### ISSUE TITLE
Video streaming capabilities in swarm formation

### ISSUE THREAD

**Issue by imsuneaik** [clydemcqueen/udp_forward#1]
Greetings,

I have been trying to display video stream capabilities in a swarm configuration (2x Tello Edu Drones) in Station Mode through python, very much similar to the one you have posted on Tellopilots forum. I do understand the workaround to this problem would be using multiple raspberry pi and allow udp forwarding through a ethernet switch. 

I found your solution (flock2) very akin to my current problem and would want to follow with it however I do have some doubts.  

My questions would be
1) May I check if it's possible to replace the ethernet switch with a spare router that I have.
2) Once I have connected to each drone's wifi using a Raspberry Pi and forward all UDP packets from the Pi to the host computer. The raspberry pi's would just provide connection with the drones and I would have to set up a linux environment on my host computer. 
3) Replacing gamepad option with command input through ROS2 CLI and if it's possible to send instructions to both the drones. 

Thank you so much for the code and efforts for the development for Tello Drones!

**Comment by clydemcqueen** [comment]
1. Probably. Depends on your router.

2. Yes.

3. You can start and stop the current mission via the ros2 CLI. But if the mission fails, or the drones are in the wrong position, you'll need a ROS-compatible joystick to manually fly a drone. See https://github.com/clydemcqueen/flock2/blob/master/src/flock_base.cpp
